### ISSUE TITLE
Duplicate dev-server logs to console

### ISSUE THREAD

**Issue by emthaw** [survivejs-demos/webpack-demo#1]
When using the latest build on master, running npm start to start the webpack-dev-server causes the server to output log messages to the console twice. Here is a screenshot of the console:
<img width="547" alt="screen shot 2016-06-28 at 12 07 46 am" src="https://cloud.githubusercontent.com/assets/20181370/16407002/38ce9078-3cc6-11e6-87d5-9fb163fa1b3c.png">

While it doesn't seem so bad the repo's current build build, once you start adding things like linting the console can quickly get unnecessarily stuffed. For example, this is Gist shows what the console looks like off of just one complete run of webpack when I'm linting my project:
https://gist.github.com/emthaw/fcc974c3f9a2b5e56bc7635078934aed

As you can see, it outputs all of the lint messages twice.

**Comment by bebraw** [comment]
The problem is that the setup relies on multiple entries and the webpack-dev-server sets up a client for each. Here's the [related code](https://github.com/webpack/webpack-dev-server/blob/a77eac516dace7f5072740206eda474a8141055b/bin/webpack-dev-server.js#L249).

I use multiple entries as otherwise you get broken hashing behavior (`chunkhash` operates per entry).

One way to solve this would be to use a single entry during development and multiple for production. That should do it.

Thanks for bringing this up!

**Comment by jadestrong** [comment]
I found during development if you add the plugin:

```
{
 plugins: [
     new webpack.optimize.CommonsChunkPlugin({
         names: ['vendor','manifest']
     })
 ]
}
```

it can fix this problem.

**Comment by bebraw** [comment]
I added the tip to the book. Thanks!

**Comment by leviathanbadger** [comment]
Are there any equivalent methods to solve this problem in webpack 4?

**Comment by bebraw** [comment]
@aboveyou00 In webpack 4 you don't need multiple entries. You can set up one and then do [bundle splitting](https://survivejs.com/webpack/building/bundle-splitting/). Webpack 4 also does some bundle splitting out of the box when run in production mode.

**Comment by leviathanbadger** [comment]
Awesome, thanks for clarifying that. I hadn't realized that that was the direction webpack was going.
