### ISSUE TITLE
Multiple Pages have lot of question

### ISSUE THREAD

**Issue by wulucxy** [survivejs-demos/webpack-demo#8]
1. where did this vendor chunk come from，what's more, did the chunk orders right？
I think the right order is: `[manifest、vendor、app]`
https://survivejs.com/webpack/output/multiple-pages/#adjusting-configuration

```javascript
 chunks: ["app", "manifest", "vendor"]
```

2. when I run `npm run build` , these is not `vendor~app` script in the html script，but if I run `npm start`，it is ok

```javascript
<script type="text/javascript" src="/manifest.725d.js"></script><script type="text/javascript" src="/app.0d0b.js"></script>
```

3. this part of description is unclear，it need to be detailed。

```javascript
If you generate a build (npm run build), you should notice that something is different compared to the first multiple page build you did. Instead of two manifest files, you can find only one. If you examine it, you notice it contains references to all files that were generated.
```

**Comment by bebraw** [comment]
> where did this vendor chunk come from，what's more, did the chunk orders right？

The order doesn't matter. It will generate the same output regardless of the order. It tells html-webpack-plugin which chunks to take into account. The `vendor` reference isn't required so I'll remove that. Thanks!

> when I run npm run build , these is not vendor~app script in the html script，but if I run npm start，it is ok

It's because the development build doesn't do bundle splitting. That's something you could change in the configuration if you prefer. The point is to avoid some processing but this might be something I should revisit.

> this part of description is unclear，it need to be detailed。

Thanks. I rewrote and combined the paragraphs. The point is that in this setup we end up with a single manifest that contains info for both pages.

Generally, webpack hasn't been optimized multi-page setups in mind. It gets a little complicated there.

Thanks for the feedback. 👍

**Comment by wulucxy** [comment]
@bebraw if I remove `vendor` from chunks field，then I run `npm run build`，it still not right。

### another/index.html

```
<script type="text/javascript" src="/manifest.7269.js"></script><script type="text/javascript" src="/another.cc96.js"></script>
```

### index.html

```
<script type="text/javascript" src="/manifest.7269.js"></script><script type="text/javascript" src="/app.dcd4.js"></script>
```
so，where‘s the vendor?

when I run the `dist` fold by `http-server`，the js never runs。I think these must be some bug here.

PS：you mean

> Instead of two manifest files, there's only one. 

but both case always get one `manifest.js`，I can't get this。

**Comment by bebraw** [comment]
I see now. Try `chunks: ["manifest", "app", "vendors~app"],` (add that last one to both). That will generate the reference.

In webpack 4, webpack generates the vendor chunk automatically and names it like that.

**Comment by wulucxy** [comment]
@bebraw actually another page does not need `vendor~app` chunk，and how can I change the `vendors~app` name to others?

what‘s more，it is so inefficient to name the chunk by hand，do we have a more automation solution?

**Comment by bebraw** [comment]
> what‘s more，it is so inefficient to name the chunk by hand，do we have a more automation solution?

One way to do that would be to set the chunk name in webpack bundle splitting configuration and then write wiring around in such way that that it gets set in both places. I am not aware of a better way for now.
